[openai]
api_key = "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"

[huggingface]
api_key = "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"
model = "nvidia/Llama-3.3-Nemotron-Super-49B-v1.5"
api_url = "https://api-inference.huggingface.co/models/nvidia/Llama-3.3-Nemotron-Super-49B-v1.5"
